apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: default
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 5
      failureLimit: 2
      successCondition: len(result) == 0 || result[0] <= 0.02
      provider:
        prometheus:
          address: http://prometheus-service.monitoring.svc.cluster.local:9090
          query: |
            rewear:http_requests:error_ratio

    - name: latency-p95
      interval: 30s
      count: 5
      failureLimit: 2
      successCondition: len(result) == 0 || result[0] <= 1.0
      provider:
        prometheus:
          address: http://prometheus-service.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))

    - name: cpu-usage
      interval: 30s
      count: 5
      failureLimit: 2
      successCondition: len(result) == 0 || result[0] <= 0.8
      provider:
        prometheus:
          address: http://prometheus-service.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{pod=~"rewear-backend-.*"}[5m])) by (pod)        

    - name: memory-usage
      interval: 30s
      count: 5
      failureLimit: 2
      successCondition: result[0] < 0.8
      provider:
        prometheus:
          address: http://prometheus-service.monitoring.svc.cluster.local:9090
          query: |
            sum(container_memory_usage_bytes{pod=~"rewear-backend.*"})        