apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: default
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: result[0] <= 0.02
      # failureCondition: result >= 0.02  
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local:9090
          query: |
            rewear:http_requests:error_ratio 
            # > avg_over_time(rewear:http_requests:error_ratio[15m]) * 2
      

    - name: latency-p95
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: result[0] <= 1.0
      provider:
        prometheus:
          query: |
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))
            address: http://prometheus-server.monitoring.svc.cluster.local:9090