replicaCount: 2
frontendUrl: "https://d1zdaauu493bq4.cloudfront.net"
backendUrl: "https://dnngvazz5ia4g.cloudfront.net"
image:
  repository: "724772062958.dkr.ecr.us-east-1.amazonaws.com/rewear-backend"
  tag: "3f2f9be8"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5001
containerPort: 5001
mongodb:
  uriSecretName: mongo-secret
  uriSecretKey: uri
  mongoUser: "admin"
env:
  NODE_ENV: "production"
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
jwtSecretName: jwt-secret
jwtSecretKey: jwt_secret
nodeSelector:
  role: ec2
tolerations: []
affinity: {}
alertmanager:
  webhookUrl: "https://5sy5ibdcp6.execute-api.us-east-1.amazonaws.com/dev/alert"
