apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.monitoring.svc.cluster.local:9090
        isDefault: true

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards

  pod-metrics.json: |
    {
      "title": "Pod Metrics",
      "panels": [
        {
          "title": "CPU Usage",
          "type": "graph",
          "targets": [
            { "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[2m])) by (pod)" }
          ]
        },
        {
          "title": "Memory Usage",
          "type": "graph",
          "targets": [
            { "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (pod)" }
          ]
        },
        {
          "title": "Container Restarts",
          "type": "graph",
          "targets": [
            { "expr": "sum(kube_pod_container_status_restarts_total) by (pod)" }
          ]
        },
        {
          "title": "Service Requests",
          "type": "graph",
          "targets": [
            { "expr": "sum(rate(http_requests_total[2m])) by (service)" }
          ]
        }
      ]
    }
